name: inz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.2
  dartz: ^0.9.2
  get: ^3.13.2
  connectivity: ^0.4.9+3
  dio: ^3.0.7
  json_serializable: ^3.2.5
  numberpicker: ^1.3.0
  flutter_svg: ^0.17.3+1
  image_picker: ^0.6.7+15
  camera: ^0.7.0
  tflite: ^1.1.1
  permission_handler: ^5.0.1+1
  rxdart: ^0.25.0
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  freezed: ^0.12.7
  injectable: ^1.1.2
  get_it: ^5.0.6
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  build_runner: ^1.10.7
  injectable_generator: null


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/tf/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf